#!/bin/bash

is_default_scanner_available() {
  scanline -list | grep -q "$scanner_name"
}

main() {
  local output_name="$1"
  local output_resolution="$2"

  local output_directory="$FLOWS_SCANS"
  local scanner_name="$SCANNER_DEFAULT"

  [[ -z "$output_name" ]] && local output_name=$(date +"%Y-%m-%d-%H%M%S")
  [[ -z "$output_resolution" ]] && local output_resolution="400"

  cd "$output_directory"

  local args=( -flatbed -batch -resolution "$output_resolution" -dir "$output_directory" -name "$output_name" )
  is_default_scanner_available && args=( -scanner "$scanner_name" "${args[@]}" )

  scanline "${args[@]}"
}

main "$@"

