#!/bin/zsh

#----------------
# Name          : config_llm
# Description   : Custom configuration for LLM interaction
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Claude Code | MiniMax

### Configure Claude Code

export ANTHROPIC_BASE_URL="https://api.minimax.io/anthropic"
export ANTHROPIC_AUTH_TOKEN="$MINIMAX_API_KEY"
export ANTHROPIC_API_KEY=""

### Override Anthropic Defaults With Custom Models

export ANTHROPIC_DEFAULT_HAIKU_MODEL="MiniMax-M2.5"
export ANTHROPIC_DEFAULT_SONNET_MODEL="MiniMax-M2.7"
export ANTHROPIC_DEFAULT_OPUS_MODEL="MiniMax-M2.7"

## Claude Code | OpenRouter

### Configure Claude Code

#export ANTHROPIC_BASE_URL="https://openrouter.ai/api"
#export ANTHROPIC_AUTH_TOKEN="$OPENROUTER_API_KEY"
#export ANTHROPIC_API_KEY=""

### Override Anthropic Defaults With Custom Models

#export ANTHROPIC_DEFAULT_HAIKU_MODEL="minimax/minimax-m2.5"
#export ANTHROPIC_DEFAULT_SONNET_MODEL="minimax/minimax-m2.7"
#export ANTHROPIC_DEFAULT_OPUS_MODEL="qwen/qwen3-coder-next"

