vim.keymap.set("n", "<leader>wt", "<cmd>tabnew<cr>", { desc = "New Tab" })
vim.keymap.set("n", "<M-j>", function()
  _G.fugitive_diff_nav("cnext")
end)
vim.keymap.set("n", "<M-k>", function()
  _G.fugitive_diff_nav("cprev")
end)
