#!/bin/zsh

#----------------
# Name          : common
# Description   : Common configuration for ZSH environments
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Environment

### Env File

#### Read the 1st line of the file to get the environment name

export ENV_NAME="$(head -n 1 $HOME/.env_name)"

### Zsh
 
#### Zsh root directory

export ZZSH="$HOME/.zsh"

#### Zsh environment directory

export ZENV="$ZZSH/env"

#### Zsh scripts directory

export ZSCRIPTS="$ZZSH/scripts"

#### Zsh plugins directory

export ZPLUGS="$ZZSH/plugins"

#### Zsh files scripts directory

export ZFS="$ZSCRIPTS/filesystem"

### Create env_id file

export ENV_ID="$($ZSCRIPTS/environment/env_id_get)"

### Specify the location of the .zcompdump file

export ZSH_COMPDUMP="$HOME/.cache/.zcompdump-${ENV_ID}-${ZSH_VERSION}"S

### Load environment-specific configuration

source "$ZENV/$ENV_NAME"

### Treat non-prefixed commands as `cd`

setopt autocd

### Initialize completion system

autoload -Uz compinit && compinit

### Starship Shell

#### Load
#
eval "$(starship init zsh)"

### FZF Fuzzy Picker

#### Display hidden files by default

setopt GLOB_DOTS
zstyle ':completion:*' extra-search-path .

### Zoxide Enhanced cd

eval "$(zoxide init --cmd cd zsh)"

### Eza Enhanced ls

alias ls='eza --icons --group-directories-first'
alias la='eza -la --icons --group-directories-first'
alias l='eza -la --icons --group-directories-first'
alias ll='eza -l --icons --group-directories-first'
alias lt='eza --tree --icons'

## System

### Shell

export SHELL="zsh"

### Editor

export EDITOR="vim"

### Language

export LANG="en_US.UTF-8"

### Preserve natural sort order

export LC_COLLATE="C"

### The current year

export THIS_YEAR=`date +"%Y"`

### Custom Mappings

#### Use Emacs mode to prevent accidental Vi-Insert

bindkey -e

#### Fix Keys

bindkey '^[[1~' beginning-of-line     # Home
bindkey '^[[4~' end-of-line           # End
bindkey '^[[3~' delete-char           # Delete
bindkey '^[[5~' up-line-or-history    # Page Up
bindkey '^[[6~' down-line-or-history  # Page Down

### Up Key | Pattern Match On History

autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

## File System

### Home

#### Desktop

export UDESK="$UHOME/Desktop"

#### Desktop

export UDOWN="$UHOME/Downloads"

#### Documents

export UDOCS="$UHOME/Documents"

#### Documents

export UPICS="$UHOME/Pictures"

### Bnk

#### Cs

export CS="$BNK/cs"

#### Hle

export HLE="$BNK/hle"

#### Snc

export SNC="$BNK/snc"

#### Scripts

export USCRIPTS="$HOME/.scripts"

#### Ensure relevant directories exist

#mkdir -p "$BNK" "$SNC" "$CS" "$HLE" > /dev/null 2>&1

### Shortcuts

#### Current Directory Path To Clipboard

alias cpwd="pwd | tr -d '\n' | pbcopy"

### Snc

#### Books

export SBOOKS="$SNC/Books"

#### Desktop

export SDESK="$SNC/Desk"

#### Desktop

export TT="$SNC/D"

#### Lg

##### Root

export SLG="$SNC/Lg"

##### Vim Mappings

export LMAPS="$SLG/.mappings"

##### Vim Snippets

export LSNIPS="$SLG/.snippets"

#### Pictures

export SPHO="$SNC/Pictures"

#### Screenshots

export SSHOTS="$SNC/Pictures/screenshots"

#### Work

export SWORK="$SNC/Work"

#### Stories

export SSTORIES="$SWORK/Stories"

### Notes

export SNOTES="$SNC/Notes"

### Snc Processes

#### Lg

snc_lg() { 
  snc_dir "Lg"
}

#### Specific directory

snc_dir() { 
  local target_dir="$1"
  [[ -d "${SNC}/${target_dir}" ]] && $ZSCRIPTS/backup/snc_init "single_dir" "$target_dir"
}

## Tools

### Open Lg session in Vim

export lg_command="$ZSCRIPTS/lg/lg_open"
alias lg="$lg_command"

### Vim

#### Vim root directory

export VVIM="$HOME/.vim"

#### Vim snippets directory

export VSNIPS="$VVIM/snippets"

### Git

#### Diff tool

if [[ `git config --global diff.tool` != "vimdiff" ]]; then
  ##### Use vim for diffing
  git config --global diff.tool vimdiff

  ##### Disable the prompt before diffing
  git config --global difftool.prompt false
fi

## Display

### Prevent partial-line %

unsetopt PROMPT_SP

## Privacy

### History

#### Maximum history items in memory

HISTSIZE=1000

#### Do not persist history to file

SAVEHIST=0

#### Unset history file location

HISTFILE=""

## Tweaks

### Always list directory contents on change

chpwd() { ls }

## Tools

### Unison

#### Ensure unique host name per machine

export UNISONLOCALHOSTNAME="$ENV_ID"

## Overrides

### Location

#### Whereami

alias whereami="curl ipinfo.io"

### Find

#### Find by file name

function ffind() { local query="$1"; find . -iname "*$query*" }

#### Find by file contents

function gfind() { local query="$1"; grep -ir "$query" }

## Files

### Cleanup

#### List `._` Files

alias dotunderls="find . -name '.**' -print"

#### Delete `._` Files

alias dotunderrm="find . -name '.**' -delete -print"

### Dot Files

#### Copy from current directory to $HOME

alias dot_files_to_home="cp -r .tmux .tmux.conf .vim .vimrc .zsh .zshenv $HOME"

#### Copy from $HOME to current directory

alias dot_files_from_home="cp -rv ~/.tmux ~/.tmux.conf ~/.vim ~/.vimrc ~/.zsh ~/.zshenv ."

## Plugins

### Antidote Plugin Manager

#### Clone Plugins $ZPLUGS

export ANTIDOTE_HOME="$ZPLUGS"

#### Load Antidote

source "$ANTIDOTE_HOME/antidote.zsh"

#### Load Plugins

antidote load "$ZZSH/plugins.txt"

### Highlighting Overrides

###### Expansion Variables ($*)

ZSH_HIGHLIGHT_STYLES[comment]=fg=yellow

