#!/bin/zsh

#----------------
# Name          : primary_macos_common
# Description   : Common configuration for Primary build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## System

### Power

#### Off

alias power_off="sudo shutdown -h now"

#### Reboot

alias power_reboot="sudo shutdown -r now"

### Update

alias system_update="system_update_macos"

## App Openers

### Browser

browser_u() { open -na 'Firefox' --args --new-window "$@" }
browser_a() { open -na 'Google Chrome' --args --new-window "$@" }

### Spreadsheet

spreadsheet() { open -na 'LibreOffice' --args --calc "$@" }

### DiskUtil

alias dlist="diskutil list"
alias dinfo="diskutil info"

source "$ZFS/rm_mac"
alias rm=rm_mac
alias srm='/bin/rm'
alias rmt='trash'
alias rmrf='trash'

