#!/bin/zsh

#----------------
# Name          : work_mac_silicon
# Description   : Shell-environment configuration for Work build in a MacOS Work environment with an M3 chip.
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Secrets

source "$ZZSH/.secrets"

### Bnk directory

export BNK="$HOME/bnk"

### CS

export CS="$BNK/cs"

### Start directory

export START="$HOME"

### Home

export UHOME="$HOME"

### Pictures

#### Root

export SP="$SNC/Pictures"

### Work

#### Root

export SW="$SNC/Work"

#### Code

export SWC="$SWORK/Code"

#### Documents

export SWD="$SWORK/Documents"

#### Notes

export SWN="$SWORK/Notes"

#### Screenshots

export SWS="$SWORK/Screenshots"

#### Tickets

export SWT="$SWORK/Tickets"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### HomeBrew

eval "$(/opt/homebrew/bin/brew shellenv)"

### VS Code

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

### asdf

export PATH="$HOME/.asdf/shims:$PATH"

### Java 21

export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"

### Vlc

alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'

## Llm

alias lm="claude"

### Vim

### Scripts

alias agile_ticket_create="$ZSCRIPTS/development/agile_ticket_create"
alias docker_clean="$ZSCRIPTS/development/docker_clean"
alias docker_rebuild="$ZSCRIPTS/development/docker_rebuild"
alias killme="$USCRIPTS/km"
graphql_generate() {
  local last_dir="$(pwd)"
  cd "$CS/backend-service"
  make frontend-generate-graphql
  cd "$last_dir"
}

## Sleep Behavior

### Prevent Sleep On Lock Screen

[[ -z `pgrep caffeinate` ]] && nohup caffeinate -d -w 1 </dev/null >/dev/null 2>&1 &!

## Boot

### Tasks

run_boot_tasks() {

}

